const Data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'Nike-slim-shirt',
      caregory: 'shirts',
      image: '/image/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas slim shirt',
      slug: 'Adidas-slim-shirt',
      caregory: 'shirt',
      image: '/image/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'ethiopian traditional Pant',
      slug: 'ethiopian traditional Pant',
      caregory: 'Pants',
      image: '/image/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality shirt',
    },
    {
      name: 'T-shirt fashion',
      slug: 'T-shirt fashion',
      caregory: 'pants',
      image: '/image/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Slim Pant',
      slug: 'Slim-Pant',
      caregory: 'Pants',
      image: '/image/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality shirt',
    },
    {
      name: 'Fashion Pant',
      slug: 'Fashion Pant',
      caregory: 'Pants',
      image: '/image/p1.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality shirt',
    },
  ],
};
export default Data;
